version: '3.8'
services:
    app:
        container_name: fieldnation-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:8000
